from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="scrapegraphai",
    version="1.52.0",
    author="wisebayes",
    description="A Python library for intelligent web scraping using graph-based approaches",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/scrapegraphai",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Internet :: WWW/HTTP :: Browsers",
        "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
    python_requires=">=3.8",
    install_requires=[
        "aiohappyeyeballs>=2.6.1",
        "aiohttp>=3.12.6",
        "aiosignal>=1.3.2",
        "annotated-types>=0.7.0",
        "anyio>=4.9.0",
        "async-timeout>=5.0.1",
        "asyncio>=3.4.3",
        "attrs>=25.3.0",
        "beautifulsoup4>=4.13.4",
        "boto3>=1.38.27",
        "botocore>=1.38.27",
        "certifi>=2025.4.26",
        "charset-normalizer>=3.4.2",
        "click>=8.2.1",
        "dataclasses-json>=0.6.7",
        "dill>=0.4.0",
        "distro>=1.9.0",
        "duckduckgo_search>=8.0.2",
        "filelock>=3.18.0",
        "free_proxy>=1.1.3",
        "frozenlist>=1.6.0",
        "fsspec>=2025.5.1",
        "greenlet>=3.2.2",
        "h11>=0.16.0",
        "hf-xet>=1.1.2",
        "html-to-markdown>=1.3.2",
        "html2text>=2025.4.15",
        "httpcore>=1.0.9",
        "httpx>=0.28.1",
        "httpx-sse>=0.4.0",
        "huggingface-hub>=0.32.3",
        "idna>=3.10",
        "jiter>=0.10.0",
        "jmespath>=1.0.1",
        "jsonpatch>=1.33",
        "jsonpointer>=3.0.0",
        "jsonschema>=4.24.0",
        "jsonschema-specifications>=2025.4.1",
        "langchain>=0.3.25",
        "langchain-aws>=0.2.24",
        "langchain-community>=0.3.24",
        "langchain-core>=0.3.63",
        "langchain-mistralai>=0.2.10",
        "langchain-ollama>=0.3.3",
        "langchain-openai>=0.3.18",
        "langchain-text-splitters>=0.3.8",
        "langsmith>=0.3.43",
        "lxml>=5.4.0",
        "marshmallow>=3.26.1",
        "minify_html>=0.16.4",
        "mpire>=2.10.2",
        "multidict>=6.4.4",
        "multiprocess>=0.70.18",
        "mypy_extensions>=1.1.0",
        "nest-asyncio>=1.6.0",
        "numpy>=2.2.6",
        "ollama>=0.5.1",
        "openai>=1.82.1",
        "orjson>=3.10.18",
        "packaging>=24.2",
        "pillow>=11.2.1",
        "playwright>=1.52.0",
        "primp>=0.15.0",
        "propcache>=0.3.1",
        "pydantic>=2.11.5",
        "pydantic-settings>=2.9.1",
        "pydantic_core>=2.33.2",
        "pyee>=13.0.0",
        "Pygments>=2.19.1",
        "python-dateutil>=2.9.0.post0",
        "python-dotenv>=1.1.0",
        "PyYAML>=6.0.2",
        "referencing>=0.36.2",
        "regex>=2024.11.6",
        "requests>=2.32.3",
        "requests-toolbelt>=1.0.0",
        "rpds-py>=0.25.1",
        "s3transfer>=0.13.0",
        "semchunk>=3.2.1",
        "simpleeval>=1.0.3",
        "six>=1.17.0",
        "sniffio>=1.3.1",
        "soupsieve>=2.7",
        "SQLAlchemy>=2.0.41",
        "tenacity>=9.1.2",
        "tiktoken>=0.9.0",
        "tokenizers>=0.21.1",
        "tqdm>=4.67.1",
        "typing-inspect>=0.9.0",
        "typing-inspection>=0.4.1",
        "typing_extensions>=4.13.2",
        "undetected-playwright>=0.3.0",
        "urllib3>=2.4.0",
        "validators>=0.35.0",
        "yarl>=1.20.0",
        "zstandard>=0.23.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0",
            "pytest-cov",
            "black",
            "isort",
            "flake8",
        ],
    },
    project_urls={
        "Bug Reports": "https://github.com/yourusername/scrapegraphai/issues",
        "Source": "https://github.com/yourusername/scrapegraphai",
    },
) 